import ContentLayout from '@/components/ContentLayout'

export const metadata = { title: 'Privacy Policy – Aura' }

const SECTIONS = [
  { title: '1. Information We Collect', body: 'We collect information you provide directly — including name, email, phone, and shipping address — as well as data generated by your use of our services (order history, browsing behaviour, wishlist items). Payment details are processed securely via SSLCommerz and are never stored on our servers.' },
  { title: '2. How We Use Your Information', body: 'Your information is used to process and fulfil orders, send order confirmations and shipping updates, personalise your shopping experience, send marketing communications (only with your consent), and improve our services and offerings.' },
  { title: '3. Data Sharing', body: 'We do not sell or rent your personal information to third parties. We share data only with our courier partners (for delivery) and payment processor (SSLCommerz), both of whom are contractually obligated to protect your data under applicable law.' },
  { title: '4. Cookies', body: 'We use essential cookies for session management and cart persistence. Analytics cookies are used only with your consent. You can manage cookie preferences in your browser settings at any time.' },
  { title: '5. Data Retention', body: 'We retain your account information for as long as your account is active. Order data is retained for 7 years for tax and legal compliance. You may request deletion of your account data by emailing privacy@aura.com.' },
  { title: '6. Your Rights', body: 'You have the right to access, rectify, erase, restrict, or port your personal data. To exercise any of these rights, please contact privacy@aura.com. We will respond within 30 days.' },
  { title: '7. Contact', body: 'For privacy-related enquiries, contact our Data Protection Officer at privacy@aura.com, or write to us at Aura Fashion House, Road 17, Banani, Dhaka 1213, Bangladesh.' },
]

export default function PrivacyPage() {
  return (
    <ContentLayout title="Privacy Policy" subtitle="Last updated: February 2026">
      <div className="space-y-6">
        {SECTIONS.map(({ title, body }) => (
          <div key={title} className="border-b border-[#F0EBE6] pb-6">
            <h3 className="font-['Playfair_Display'] text-lg text-[#0A0A0A] mb-3">{title}</h3>
            <p className="text-sm text-[#555] leading-relaxed">{body}</p>
          </div>
        ))}
      </div>
    </ContentLayout>
  )
}
